# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUT1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uT1(self):
    # Test name: UT_1
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 945x1012 |  | 
    self.driver.set_window_size(945, 1012)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | id=login-username |  | 
    self.driver.find_element(By.ID, "login-username").click()
    # 5 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 6 | type | id=login-password | @pw123456 | 
    self.driver.find_element(By.ID, "login-password").send_keys("@pw123456")
    # 7 | click | css=.cOJqPq |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".cOJqPq").click()
    # 8 | click | css=.eMzEmF |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".eMzEmF").click()
    # 9 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(3) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(3) .Type__TypeElement-sc-goli3j-0").click()
    # 10 | click | css=.w6j_vX6SF5IxSXrrkYw5 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".w6j_vX6SF5IxSXrrkYw5").click()
    # 11 | mouseOver | css=.w6j_vX6SF5IxSXrrkYw5 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".w6j_vX6SF5IxSXrrkYw5")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 12 | mouseOut | css=.w6j_vX6SF5IxSXrrkYw5 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(4) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(4) .Type__TypeElement-sc-goli3j-0").click()
    # 14 | click | css=.eMzEmF |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".eMzEmF").click()
    # 15 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(5) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(5) .Type__TypeElement-sc-goli3j-0").click()
  
