# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUI03():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_uI03(self):
    # Test name: UI_03
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 968x1031 |  | 
    self.driver.set_window_size(968, 1031)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | id=login-username |  | 
    self.driver.find_element(By.ID, "login-username").click()
    # 5 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 6 | type | id=login-password | @pw123456789 | 
    self.driver.find_element(By.ID, "login-password").send_keys("@pw123456789")
    # 7 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    # 8 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=.KdxlBanhDJjzmHfqhP0X > .Svg-sc-ytk21e-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".KdxlBanhDJjzmHfqhP0X > .Svg-sc-ytk21e-0").click()
    # 10 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0 |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 11 | selectWindow | handle=${win5268} |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0").click()
    # 12 | mouseOver | css=.mh-menu-closed |  | 
    self.vars["win5268"] = self.wait_for_window(2000)
    # 13 | mouseOut | css=.mh-menu-closed |  | 
    self.driver.switch_to.window(self.vars["win5268"])
    # 14 | mouseOver | linkText=Hồ sơ |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".mh-menu-closed")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | css=#profile > .sc-4847034f-1 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 16 | click | css=.Group-sc-u9bcx5-0:nth-child(3) .Select-sc-3qvhho-0 |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Hồ sơ")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | select | css=.Group-sc-u9bcx5-0:nth-child(3) .Select-sc-3qvhho-0 | label=Không muốn nêu cụ thể | 
    self.driver.find_element(By.CSS_SELECTOR, "#profile > .sc-4847034f-1").click()
    # 18 | click | id=dob-date |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Group-sc-u9bcx5-0:nth-child(3) .Select-sc-3qvhho-0").click()
    # 19 | type | id=dob-date | 18 | 
    dropdown = self.driver.find_element(By.CSS_SELECTOR, ".Group-sc-u9bcx5-0:nth-child(3) .Select-sc-3qvhho-0")
    dropdown.find_element(By.XPATH, "//option[. = 'Không muốn nêu cụ thể']").click()
    # 20 | click | id=dob-year |  | 
    self.driver.find_element(By.ID, "dob-date").click()
    # 21 | type | id=dob-year | 1992 | 
    self.driver.find_element(By.ID, "dob-date").send_keys("18")
    # 22 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.ID, "dob-year").click()
    # 23 | click | css=.dohplt |  | 
    self.driver.find_element(By.ID, "dob-year").send_keys("1992")
    # 24 | click | css=#overview > .sc-4847034f-1 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    self.driver.find_element(By.CSS_SELECTOR, ".dohplt").click()
    self.driver.find_element(By.CSS_SELECTOR, "#overview > .sc-4847034f-1").click()
  
