# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin04():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login04(self):
    # Test name: Login_04
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 1051x798 |  | 
    self.driver.set_window_size(1051, 798)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | id=login-username |  | 
    self.driver.find_element(By.ID, "login-username").click()
    # 5 | type | id=login-username | agx50980@nezid.com | 
    self.driver.find_element(By.ID, "login-username").send_keys("agx50980@nezid.com")
    # 6 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 7 | type | id=login-password | abcxyz123 | 
    self.driver.find_element(By.ID, "login-password").send_keys("abcxyz123")
    # 8 | mouseDown | css=.Wrapper-sc-16y5c87-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".Wrapper-sc-16y5c87-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 9 | mouseUp | css=.Indicator-sc-acu4qz-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".Indicator-sc-acu4qz-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 10 | click | css=.Wrapper-sc-16y5c87-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Wrapper-sc-16y5c87-0").click()
    # 11 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    # 12 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | click | css=.ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0").click()
    # 14 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0").click()
    # 15 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 16 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 17 | click | css=.FeWwGSRANj36qpOBoxdx |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeWwGSRANj36qpOBoxdx").click()
    # 18 | type | css=.FeWwGSRANj36qpOBoxdx | gió | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeWwGSRANj36qpOBoxdx").send_keys("gió")
    # 19 | click | css=div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0").click()
    # 20 | mouseOver | css=div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 21 | mouseOut | css=.eRuZMo_HNLjb1IalIeRb .Button-sc-y0gtbx-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 22 | click | css=.lgQSxe path |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".lgQSxe path").click()
    # 23 | close |  |  | 
    self.driver.close()
  
