# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUI04():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uI04(self):
    # Test name: UI_04
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 968x1031 |  | 
    self.driver.set_window_size(968, 1031)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | css=.sc-hLBbgP |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".sc-hLBbgP").click()
    # 5 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 6 | type | id=login-password | abcxyz123456789 | 
    self.driver.find_element(By.ID, "login-password").send_keys("abcxyz123456789")
    # 7 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    # 8 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=.KdxlBanhDJjzmHfqhP0X > .Svg-sc-ytk21e-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".KdxlBanhDJjzmHfqhP0X > .Svg-sc-ytk21e-0").click()
    # 10 | click | css=.NmbeQabkSLXf0mTAhSLl > .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".NmbeQabkSLXf0mTAhSLl > .Type__TypeElement-sc-goli3j-0").click()
    # 11 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 12 | click | id=desktop.settings.selectLanguage |  | 
    self.driver.find_element(By.ID, "desktop.settings.selectLanguage").click()
    # 13 | select | id=desktop.settings.selectLanguage | label=English (English) | 
    dropdown = self.driver.find_element(By.ID, "desktop.settings.selectLanguage")
    dropdown.find_element(By.XPATH, "//option[. = 'English (English)']").click()
    # 14 | click | css=.Button-sc-y0gtbx-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Button-sc-y0gtbx-0").click()
    # 15 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 16 | mouseOver | css=.cvTLPmjt6T7M85EKcB8w |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".cvTLPmjt6T7M85EKcB8w")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseOver | linkText=Search |  | 
    element = self.driver.find_element(By.LINK_TEXT, "Search")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | click | css=.LU0q0itTx2613uiATSig:nth-child(1) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LU0q0itTx2613uiATSig:nth-child(1) .Type__TypeElement-sc-goli3j-0").click()
    # 19 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 20 | mouseOver | css=.QyANtc_r7ff_tqrf5Bvc:nth-child(1) .a7lvtXATo3HALtrsOHtO > .Type__TypeElement-sc-goli3j-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".QyANtc_r7ff_tqrf5Bvc:nth-child(1) .a7lvtXATo3HALtrsOHtO > .Type__TypeElement-sc-goli3j-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
  
