# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUT3():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_uT3(self):
    # Test name: UT_3
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 945x1012 |  | 
    self.driver.set_window_size(945, 1012)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | id=login-username |  | 
    self.driver.find_element(By.ID, "login-username").click()
    # 5 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 6 | type | id=login-password | @pw123456 | 
    self.driver.find_element(By.ID, "login-password").send_keys("@pw123456")
    # 7 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    # 8 | click | css=.ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0").click()
    # 9 | mouseOver | css=.ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 10 | mouseOut | css=.ksmcxhImUuj3_s1lcIm0 .Svg-sc-ytk21e-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 11 | click | css=.DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".DuEPSADpSwCcO880xjUG:nth-child(1) .Type__TypeElement-sc-goli3j-0").click()
    # 12 | mouseOver | css=.xfQXUkj6ThzTYbfF8ilt |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".xfQXUkj6ThzTYbfF8ilt")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 13 | click | css=.FeWwGSRANj36qpOBoxdx |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeWwGSRANj36qpOBoxdx").click()
    # 14 | type | css=.FeWwGSRANj36qpOBoxdx | baby | 
    self.driver.find_element(By.CSS_SELECTOR, ".FeWwGSRANj36qpOBoxdx").send_keys("baby")
    # 15 | click | css=div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0").click()
    # 16 | mouseOver | css=div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(1) > .h4HgbO_Uu1JYg5UGANeQ .Button-sc-y0gtbx-0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 17 | mouseOut | css=.eRuZMo_HNLjb1IalIeRb .Button-sc-y0gtbx-0 |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 18 | mouseOver | css=.JzyZE2R09wq7xtjECDeR path |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".JzyZE2R09wq7xtjECDeR path")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 19 | mouseOver | css=.iPiseC |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".iPiseC")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 20 | close |  |  | 
    self.driver.close()
  
