# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin03():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login03(self):
    # Test name: Login_03
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 806x816 |  | 
    self.driver.set_window_size(806, 816)
    # 3 | click | css=.LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".LKFFk88SIRC9QKKUWR5u .ButtonInner-sc-14ud5tc-0").click()
    # 4 | click | id=login-username |  | 
    self.driver.find_element(By.ID, "login-username").click()
    # 5 | type | id=login-username | csu181606@zslsz.com | 
    self.driver.find_element(By.ID, "login-username").send_keys("csu181606@zslsz.com")
    # 6 | click | id=login-password |  | 
    self.driver.find_element(By.ID, "login-password").click()
    # 7 | type | id=login-password | abcxyz123 | 
    self.driver.find_element(By.ID, "login-password").send_keys("abcxyz123")
    # 8 | click | css=.Wrapper-sc-16y5c87-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Wrapper-sc-16y5c87-0").click()
    # 9 | click | css=.ButtonInner-sc-14ud5tc-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".ButtonInner-sc-14ud5tc-0").click()
    # 10 | click | css=.Message-sc-15vkh7g-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Message-sc-15vkh7g-0").click()
    # 11 | close |  |  | 
    self.driver.close()
  
