# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSignup02():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_signup02(self):
    # Test name: Signup_02
    # Step # | name | target | value | comment
    # 1 | open | / |  | 
    self.driver.get("https://open.spotify.com/")
    # 2 | setWindowSize | 1054x800 |  | 
    self.driver.set_window_size(1054, 800)
    # 3 | mouseOver | css=.jVdqg |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".jVdqg")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 4 | click | css=.jVdqg |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".jVdqg").click()
    # 5 | runScript | window.scrollTo(0,1.600000023841858) |  | 
    self.driver.execute_script("window.scrollTo(0,1.600000023841858)")
    # 6 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 7 | runScript | window.scrollTo(0,200) |  | 
    self.driver.execute_script("window.scrollTo(0,200)")
    # 8 | type | id=email | cja17846@zslsz.com | 
    self.driver.find_element(By.ID, "email").send_keys("cja17846@zslsz.com")
    # 9 | click | id=password |  | 
    self.driver.find_element(By.ID, "password").click()
    # 10 | type | id=password | @pw123456 | 
    self.driver.find_element(By.ID, "password").send_keys("@pw123456")
    # 11 | click | id=displayname |  | 
    self.driver.find_element(By.ID, "displayname").click()
    # 12 | type | id=displayname | Xuan Hoan | 
    self.driver.find_element(By.ID, "displayname").send_keys("Xuan Hoan")
    # 13 | click | id=day |  | 
    self.driver.find_element(By.ID, "day").click()
    # 14 | type | id=day | 11 | 
    self.driver.find_element(By.ID, "day").send_keys("11")
    # 15 | click | id=month |  | 
    self.driver.find_element(By.ID, "month").click()
    # 16 | select | id=month | label=Tháng 7 | 
    dropdown = self.driver.find_element(By.ID, "month")
    dropdown.find_element(By.XPATH, "//option[. = 'Tháng 7']").click()
    # 17 | click | id=year |  | 
    self.driver.find_element(By.ID, "year").click()
    # 18 | type | id=year | 2002 | 
    self.driver.find_element(By.ID, "year").send_keys("2002")
    # 19 | click | css=.Radio-sc-tr5kfi-0:nth-child(1) .Indicator-sc-hjfusp-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Radio-sc-tr5kfi-0:nth-child(1) .Indicator-sc-hjfusp-0").click()
    # 20 | click | css=.Group-sc-u9bcx5-0:nth-child(6) .Indicator-sc-1airx73-0 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".Group-sc-u9bcx5-0:nth-child(6) .Indicator-sc-1airx73-0").click()
    # 21 | click | css=.dqLIWu |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".dqLIWu").click()
    # 22 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 23 | runScript | window.scrollTo(0,0) |  | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 24 | close |  |  | 
    self.driver.close()
  
